name: "Bug Report"
description: "File a bug report"
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this bug report!"

  - type: input
    id: contact
    attributes:
      label: "Contact Details"
      description: "How can we get in touch with you if we need more info?"
      placeholder: "ex. email@example.com"
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: "What happened?"
      description: "Also tell us, what did you expect to happen?"
      placeholder: "Tell us what you see!"
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
    validations:
      required: true
  - type: dropdown
    id: devices
    attributes:
      label: What Alexa device are you using?
      multiple: true
      options:
        - Echo
        - Echo Show
        - Fire TV
        - Other
  - type: input
      id: other-device
      attributes:
        label: Other Device
        description: If you selected other in devices dropdown please let us know which one did you use!
      validations:
        required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true